## This is the default, creating all the OS/CPU/Packages listed on the front readme.md
#profile = "default"
## Setting `custom` will make no default packs. You need to configure them manually
## profile = "custom"
## Store the artifacts to `myfolder`
#artifacts_folder = "myfolder"

# configuration file for dotnet-releaser
[msbuild]
project = "ConfluenceApiV2.sln"
[github]
user = "HendrikKoelbel"
repo = "ConfluenceApiV2"
version_prefix = "v"
[nuget]
source = "https://api.nuget.org/v3/index.json"
publish = true
publish_draft = false


# Changelog categories
[[changelog.category]]
title = "## 🚨 Breaking Changes"
labels = ["breaking-change", "category: breaking-change"]
order = 10

[[changelog.category]]
title = "## ✨ New Features"
labels = ["new-feature", "feature", "category: feature"]
order = 20

[[changelog.category]]
title = "## 🐛 Bug Fixes"
labels = ["bugfix", "fix", "bug", "category: bug"]
order = 30

[[changelog.category]]
title = "## 🚀 Enhancements"
labels = ["enhancement", "refactor", "performance", "category: performance", "category: enhancement"]
order = 40

[[changelog.category]]
title = "## 🧰 Maintenance"
labels = ["maintenance", "ci", "category: ci"]
order = 50

[[changelog.category]]
title = "## 🏭 Tests"
labels = ["tests", "test", "category: tests"]
order = 60

[[changelog.category]]
title = "## 🛠 Examples"
labels = ["examples", "samples", "category: samples", "category: examples"]
order = 70

[[changelog.category]]
title = "## 📚 Documentation"
labels = ["documentation", "doc", "docs", "documentations", "category: documentation", "category: doc"]
order = 80

[[changelog.category]]
title = "## 🌎 Accessibility"
labels = ["translations", "accessibility", "category: accessibility"]
order = 90

[[changelog.category]]
title = "## 📦 Dependencies"
labels = ["dependencies", "deps", "category: dependencies"]
order = 100

[[changelog.category]]
title = "## 🧰 Misc"
labels = ["misc", "category: misc"]
order = 110

# Changelog auto-labelers
[[changelog.autolabeler]]
label = "breaking-change"
title = '^.*\b([Bb]reaking\s+[Cc]hange)\b.*$'
# Example: "Breaking Change: API no longer supports v1 endpoints"

[[changelog.autolabeler]]
label = "maintenance"
title = '^.*\b(([Aa]dd|[Aa]dded|[Ii]mprove|[Ii]mproved|[Ff]ix|[Ff]ixed|[Uu]pdate|[Uu]pdated))\b.*\b(ci)\b.*$|^.*\b(ci)\b.*\b(([Aa]dd|[Aa]dded|[Ii]mprove|[Ii]mproved|[Ff]ix|[Ff]ixed|[Uu]pdate|[Uu]pdated))\b.*$'
# Examples: "Add ci pipeline", "Fixed ci error", "Updated ci configuration", "ci updated to fix errors", "ci added to project"

[[changelog.autolabeler]]
label = "documentation"
title = '^.*\b(([Aa]dd|[Aa]dded|[Ii]mprove|[Ii]mproved|[Ff]ix|[Ff]ixed|[Uu]pdate|[Uu]pdated))\b.*\b([Dd]oc|[Dd]ocs|[Dd]ocumentation|[Dd]ocumentations)\b.*$|^.*\b([Dd]oc|[Dd]ocs|[Dd]ocumentation|[Dd]ocumentations)\b.*\b(([Aa]dd|[Aa]dded|[Ii]mprove|[Ii]mproved|[Ff]ix|[Ff]ixed|[Uu]pdate|[Uu]pdated))\b.*$'
# Examples: "Added documentation for new feature", "Fixed typos in doc", "Updated README.md", "README.md updated in the documentation", "docs added to the project"

[[changelog.autolabeler]]
label = "tests"
title = '^.*\b(([Aa]dd|[Aa]dded|[Ii]mprove|[Ii]mproved|[Ff]ix|[Ff]ixed|[Uu]pdate|[Uu]pdated))\b.*\b([Tt]est|[Tt]ests)\b.*$|^.*\b([Tt]est|[Tt]ests)\b.*\b(([Aa]dd|[Aa]dded|[Ii]mprove|[Ii]mproved|[Ff]ix|[Ff]ixed|[Uu]pdate|[Uu]pdated))\b.*$'
# Examples: "Added unit tests", "Fixed test cases", "Updated test suite", "test suite improved", "tests added to the project"

[[changelog.autolabeler]]
label = "examples"
title = '^.*\b(([Aa]dd|[Aa]dded|[Ii]mprove|[Ii]mproved|[Ff]ix|[Ff]ixed|[Uu]pdate|[Uu]pdated))\b.*\b([Ee]xample|[Ee]xamples)\b.*$|^.*\b([Ee]xample|[Ee]xamples)\b.*\b(([Aa]dd|[Aa]dded|[Ii]mprove|[Ii]mproved|[Ff]ix|[Ff]ixed|[Uu]pdate|[Uu]pdated))\b.*$'
# Examples: "Added usage examples", "Improved code examples", "Fixed example scripts", "example scripts added", "examples added to the project"

[[changelog.autolabeler]]
label = "accessibility"
title = '^.*\b(([Aa]dd|[Aa]dded|[Ii]mprove|[Ii]mproved|[Ff]ix|[Ff]ixed|[Uu]pdate|[Uu]pdated))\b.*\b([Aa]ccessibility|[Tt]ranslation|[Tt]ranslations)\b.*$|^.*\b([Aa]ccessibility|[Tt]ranslation|[Tt]ranslations)\b.*\b(([Aa]dd|[Aa]dded|[Ii]mprove|[Ii]mproved|[Ff]ix|[Ff]ixed|[Uu]pdate|[Uu]pdated))\b.*$'
# Examples: "Added accessibility features", "Updated translations", "Improved accessibility support", "translations added", "accessibility improved in the project"

[[changelog.autolabeler]]
label = "bugfix"
title = '^.*\b(([Ff]ix|[Ff]ixed|[Bb]ugfix))\b.*$|^.*\b(([Aa]dd|[Aa]dded|[Ii]mprove|[Ii]mproved|[Uu]pdate|[Uu]pdated))\b.*\b([Bb]ugfix|[Bb]ug)\b.*$'
# Examples: "Fixed a bug in authentication", "Bugfix: corrected null reference error", "authentication bug fixed", "bugfix added to project"

[[changelog.autolabeler]]
label = "feature"
title = '^.*\b([Aa]dd|[Aa]dded)\b.*$|^.*\b(([Aa]dd|[Aa]dded))\b.*\b([Ff]eature|[Ff]eatures)\b.*$|^.*\b([Ff]eature|[Ff]eatures)\b.*\b(([Aa]dd|[Aa]dded))\b.*$'
# Examples: "Added new endpoint for user data", "Add support for OAuth2", "new feature added", "feature added to project"

[[changelog.autolabeler]]
label = "enhancement"
title = '^.*\b(([Ee]nhance|[Rr]efactor|[Rr]efactored|[Ii]mprove|[Ii]mproved))\b.*\b([Pp]erformance|[Pp]erf|[Ee]nhancement|[Ee]nhancements)\b.*$|^.*\b([Pp]erformance|[Pp]erf|[Ee]nhancement|[Ee]nhancements)\b.*\b(([Ee]nhance|[Rr]efactor|[Rr]efactored|[Ii]mprove|[Ii]mproved))\b.*$'
# Examples: "Enhanced logging", "Refactored authentication module", "Improved performance of data processing", "performance improvement added", "enhancements added to project"

[[changelog.autolabeler]]
label = "dependencies"
title = '^.*\b([Uu]pdate|[Uu]pdated)\b.*\b([Dd]epend|[Dd]ependencies)\b.*$|^.*\b([Dd]epend|[Dd]ependencies)\b.*\b([Uu]pdate|[Uu]pdated)\b.*$|^.*\b([Bb]ump)\b.*\w{3,}.*$'
# Examples: "Updated dependencies", "Bump version of Newtonsoft.Json", "dependencies updated", "dependencies updated in the project"

[[changelog.autolabeler]]
label = "misc"
title = '.*'
# Example: Any other commit message not matching the above patterns